### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by expipiplus1** [simonmichael/gist#1]
Hopefully raising the upper bounds on the dependencies will allow this to compile again.

**Comment by simonmichael** [comment]
I think this stopped working due to some github API change. I still need this and I'd love to have it updated and fulfilling its goal. Nowadays it could probably be a one-file stack script. Would you be interested in taking a crack at it ?

**Comment by expipiplus1** [comment]
I can put it on my todo list, but probably won't be able to get down to it for a while :)

If you're looking for a cli gist client I can recommend https://github.com/defunkt/gist

**Comment by simonmichael** [comment]
I made mine because that one let me down in some way, but I should give it another try. Thanks!

**Comment by expipiplus1** [comment]
I was checking out this one for the same reason :)

**Comment by simonmichael** [comment]
Now compiles again (but doesn't work).

**Comment by expipiplus1** [comment]
Thanks :)
